# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Murilo Erhardt
user_description: MEAN stack developer (Mongo, Express, Angular, Node), worked with mobile and web projects, and also as a business analyst. Student of Apple Developer Academy (ADA), also has experience with iOS development.  
user_title: Full Stack Developer
email: murilo0121@gmail.com
linkedinUser: https://www.linkedin.com/in/murilo-erhardt-a01a6bb0/
github_username:  https://github.com/muriloe
facebookUser:  https://www.facebook.com/muriloe

# Google-analytics
google-analytics:
  id: "UA-138371399-1"

exclude: ['package.json', 'src' , 'node_modules']
